apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    giantswarm.io/cluster: ${workload_cluster_name}
    giantswarm.io/managed-by: flux
  name: hello-world
  namespace: demo0
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: false
  name: hello-world-app
  namespace: hello-world
  version: 0.2.0
