apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    giantswarm.io/cluster: ${workload_cluster_name}
    giantswarm.io/managed-by: flux
  name: ${cluster_name}-hello-world-app-auto
  namespace: org-${organization}
spec:
  catalog: giantswarm-catalog-oci
  kubeConfig:
    inCluster: false
  name: hello-world
  namespace: hello-world-auto
  version: 3.2.2 # {"$imagepolicy": "org-${organization}:${cluster_name}-hello-world:tag"}
