apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${cluster_name}-hello-world-app-auto
  namespace: org-${organization}
spec:
  interval: 10m
  provider: generic
  ref:
    tag: 3.2.2 # {"$imagepolicy": "org-${organization}:${cluster_name}-hello-world:tag"}
  url: oci://gsoci.azurecr.io/charts/giantswarm/hello-world
