apiVersion: v1
data:
  values: |-
    sources:
    - name: my-repository
      interval: 1m
      branch: main
      url: https://github.com/my-repository
      provider: github
      credentials:
        username: fakeuser
        token: faketoken
    kustomizations:
    - name: my-kustomizations
      interval: 1m
      path: "./management-clusters/MC_NAME/organizations/${organization}/workload-clusters/${cluster_id}/to_be_created_in_WC"
      prune: false
      source_name: my-repository
kind: ConfigMap
metadata:
  name: ${cluster_id}-flux-app-user-values
