apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-default-apps
  namespace: org-${organization}
spec:
  userConfig:
    configMap:
      name: ${cluster_name}-default-apps-userconfig
      namespace: org-${organization}
