---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: ${cluster_name}-hello-app
  namespace: org-${organization}
spec:
  image: giantswarmpublic.azurecr.io/giantswarm-catalog/hello-world-app
  interval: 10m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: ${cluster_name}-simple-db-app
  namespace: org-${organization}
spec:
  image: giantswarmpublic.azurecr.io/giantswarm-catalog/simple-db-app
  interval: 10m0s
