apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_id}-simple-db
spec:
  catalog: giantswarm
  config:
    configMap:
      name: ${cluster_id}-simple-db-values
  kubeConfig:
    inCluster: false
  name: simple-db-app
  version: 0.1.0
