apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
kind: Kustomization
patchesStrategicMerge:
- awscluster.yaml
resources:
- ../../../../../../../bases/clusters/aws/v1alpha3
#- ../../../../../../../bases/nodepools/aws/v1alpha3
