apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-nginx-ingress-controller
  namespace: org-${organization}
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: false
  name: nginx-ingress-controller-app
  namespace: kube-system
  userConfig:
    configMap:
      name: ${cluster_name}-nginx-ingress-controller-user-values
      namespace: org-multi-project
  version: 2.8.0
