apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${cluster_name}-ingress-nginx
  namespace: org-${organization}
spec:
  interval: 10m
  provider: generic
  ref:
    tag: 4.3.5
  url: oci://gsoci.azurecr.io/charts/giantswarm/ingress-nginx
