apiVersion: infrastructure.giantswarm.io/v1alpha3
kind: AWSCluster
metadata:
  name: ${cluster_id}
  namespace: org-${organization}
spec:
  cluster:
    description: "GitOps Demo Cluster from Cluster Template"
