apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
commonLabels:
  giantswarm.io/managed-by: flux
configMapGenerator:
  - files:
      - values=override_config_hello_world.yaml
    name: ${cluster_id}-hello-world-user-values
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
namespace: hello-web-team1
patchesStrategicMerge:
  - patch_app_config.yaml
resources:
  - ../../../../../../../../../bases/app_sets/hello-web-app
