apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-hello-world
spec:
  userConfig:
    configMap:
      name: ${cluster_name}-hello-world-user-values
      namespace: hello-world-app
