apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
configMapGenerator:
  - files:
      - values=nginx-from-template/override_config_nginx_ingress_controller.yaml
    name: ${cluster_id}-nginx-ingress-controller-user-values
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
patchesStrategicMerge:
  - nginx-from-template/patch_nginx_ingress_config.yaml
resources:
  - ../../../../../../../bases/cluster_templates/hello_app_cluster
  - nginx-from-template/override_secret_nginx_ingress_controller.enc.yaml
