apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-nginx-ingress-controller
  namespace: kube-system
spec:
  catalog: giantswarm
  config:
    configMap:
      name: ${cluster_name}-nginx-ingress-controller-values
      namespace: kube-system
  kubeConfig:
    inCluster: false
  name: nginx-ingress-controller-app
  namespace: kube-system
  version: 2.8.0
