apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_id}-nginx-ingress-controller
spec:
  catalog: giantswarm
  config:
    configMap:
      name: ${cluster_id}-nginx-ingress-controller-values
  kubeConfig:
    inCluster: false
  name: nginx-ingress-controller-app
  namespace: kube-system
  version: 2.8.0
