apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-nginx-ingress-controller
  namespace: org-${organization}
spec:
  catalog: giantswarm
  extraConfigs:
    - kind: configMap
      name: ${cluster_name}-nginx-ingress-controller-values
      namespace: org-${organization}
      priority: 1
  kubeConfig:
    inCluster: false
  name: nginx-ingress-controller-app
  namespace: kube-system
  version: 2.8.0
