apiVersion: v1
data:
    values: ENC[AES256_GCM,data:+FHLttEALHf/kJX0KJgizJ0oCDyl0tI6XdoUMdS8Md8GZLldkBwKNyq2ItB2f60PvTVdSu9g9/6OjnoLHh8osXLTTwrvZ890M3Q0AuZiZ7JNsj7ZRtb18Zo8+6Gwl9j8nB5Mng==,iv:qF5lzVOxHRc6Dp4rT1hOHnDbnFltOkNbTlajSTrFcCc=,tag:libZcccc86jEw+yoZAZr0A==,type:str]
kind: Secret
metadata:
    name: ${cluster_name}-gateway-api-config-user-secrets
    namespace: org-${organization}
type: Opaque
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T17:32:36Z"
    mac: ENC[AES256_GCM,data:p4aCHU/2aiK8yqvfjSFmwzq8zzEvMaebEhWVXbF7hlspysLNLCSPajPbQHVA3UmkZ+Y57wGg7gdXxX/OPlkL3zCOuBFKh3iYpNqeZb6Rpm5fjO6efAZ2IAZxSLq24qdZf416O9jI/n90yphuHF6iTm5MuxU7AW5W36YJXt8iC1M=,iv:Ynkn4QnOmTRYNiZ49HtGYXRlNUdRgNDvNGDrICeOY1w=,tag:mNRJ0vYeQCQaRBR0uaRbcw==,type:str]
    pgp:
        - created_at: "2026-09-29T17:32:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6N+LWItkVcPARAAvD/N6vm5vkoekYJIxQYzGTYLSdG/KfEhhEKvsBvunvK2
            qN+lVCDs0eBaTj9tLZn9Vvw2frJZsKrazlyso7zQStFGllISqUQvwa9RwJurIUDU
            avyu6egKlf65dn68b9NZI2vOiL72Qfmd9K8qrybi14xFR6umUVfWEmFqCCUSn6H/
            1hmFC21uZ9lJo7F05rhtYtugjF3cPehWguCSFkZk2kZAJUAiqxY8q9JUNzw5cvVY
            ZhHN5u2swPqGAUYy2ZBSxPfgNnuyP/qNt2Iy4yuY3qdfIweepuuveQbGAhrjSatv
            021TbBDKBKJx2QuPPPDETSvu8FaqNdmdN4hxMOHnTfnrcvctkm/7JSEs4CkIkICj
            72DkxpgiwJqeJSnvQTB383NURJ3aLL781iPoBG71OM5Tdx44M4b2PL9EMykME2Av
            9zqXDtFmLbJlgeJfd+GPPCOWQlvooZ+4r8UGBRHu14WSQICXaS8EWBZPxSOSKxdM
            4tDzIUy6H8FywBFDKuNwvpFq4KQRCSyhe+aVykUYAvLI1YYrpZtsF1LBaoevJUI3
            XMrttuComSx1wxcvymlCaGavk5Foe72FA4czZaw7oDjUOTZ4aVp0f0KUKk1zbNYm
            WRuyMwqzHGtyf3BP5zBt8aYHFUoKd57QxIX6M3a/McEw6v+0Ptp1GdwVUopNgNnS
            XgHMnd2vdHrF3BZaTz/jBSD6cm4mWRYQwRjP7Qh4tST6Bu0dUlucBFsxI+S4JV40
            2ez3gxAZlDoupv/SOeCbEbJMnirfOg7whkYyDHkLjrPAhGpxBX8T4AAOMvtOAs4=
            =8DsK
            -----END PGP MESSAGE-----
          fp: F385A8645CA55C0AA5D1263D9B05BF264528D991
    version: 3.13.3
