apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
commonLabels:
  giantswarm.io/managed-by: flux
kind: Kustomization
patchesStrategicMerge:
  - patch_user_config.yaml
resources:
  - ../../../clusters/capo/>=v0.6.0
  - cluster_user_config.yaml
