apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ${workload_cluster_name}
  namespace: default
spec:
  interval: 1m
  path: "./management-clusters/MC_NAME/organizations/ORG_NAME/workload-clusters/WC_NAME"
  postBuild:
    substitute:
      cluster_id: "${workload_cluster_id}"
      control_plane_id: "${control_plane_id}"
      machine_deployment_id: "${machine_deployment_id}"
      organization: "${organization}"
      release: "16.3.1"
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: ${gitops_repo}
  timeout: 2m
