apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
commonLabels:
  giantswarm.io/managed-by: flux
kind: Kustomization
namespace: org-${organization}
resources:
  - nginx-from-template/
