apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
commonLabels:
  giantswarm.io/managed-by: flux
kind: Kustomization
patchesStrategicMerge:
- patch_awscluster.yaml
resources:
- ../../../../../../../../bases/clusters/aws/v1alpha3
#- ../../../../../../../../bases/nodepools/aws/v1alpha3
