apiVersion: v1
data:
    values: ENC[AES256_GCM,data:HdU6EQ4uF4kYFt6Sg3IEtGRWyPNg97JO9dhhWwhb4rv2jQ8JlPczb+NAjVjbxSd5mn7E0tqhbOk73aXv052z/y+YQ5bZUzhV6BibNIMqnzlG11YEXa9UBJLCJGfsLUFAT/ycDQ==,iv:M2K7xzzZJPz+mrx/oP94hJGSsKZmU9fOkDCDVKWn8M8=,tag:Kn7ndhDyGRuQh101c/IM1Q==,type:str]
kind: Secret
metadata:
    name: ${cluster_name}-gateway-api-config-user-secrets
    namespace: org-${organization}
type: Opaque
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T17:32:36Z"
    mac: ENC[AES256_GCM,data:hjBS0zksGW3UOAQy9pAiCFV9ZBNwb/ayNWFd+pGdVb/Zt0pkqyCqXxCI86wX67d//4EcDOeKzaoQQy5Rhy5Sd+tztCip4RvAEy9mH1QrZVipZX/obJQ06jUGa9VS2+pvcrqeNX+FCFd886v9aRXjyhqK5jT4xuucJyVQdrfECzI=,iv:8xm4vmlA3g4XZZVo7XesJd17cOEcMFDa0gPMiGjHRTE=,tag:gqxz8flcZ8e3RTpWGBUuNg==,type:str]
    pgp:
        - created_at: "2026-09-29T17:32:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6N+LWItkVcPARAAsAeEoeiAgSFYNZJDRHu0pUZ8QFAo7xGjt5S3vLfv94pK
            iAi9IbqDfNvbme+boDVEwF2kJwCwu9CapBsDhk+O9ALDamS+a3VwYoUK8uTdioF9
            3HNby/7fHjhB2FiApNBhPe718laPu+2wZ4jwW34D3fNE5n1/5edw3cIp49xO7uT7
            2QMgAkCNNj8Wm+ITDvl2A8tnKKMJRH9jQFamNAlTMss7saeBzeZns1oX9jA4ZnnZ
            F7wmNwMHxDs8wRUqb9uAmN02K9oiZjeyOeptzUvLYafas1cJrrdQAe621cO708Y+
            N+uYCSMcDknT11P5nnDCgh/2AAgclCsc5FgxUo8sPxDlsh38dx4OuiIrLaXQR9k1
            8IwaS0+8zCblAPJoCF6K2l8G2gsV+MYUlLVmFwFsIUfu4z7rYWlnV91FLcgU2w2u
            JJ3bhwADlpBOm+f4OzIaav/6TTl31Tdp/zzpxf45MXRqc145PV+7yTQdvIN3iwQo
            AS9FA/413rowUbQP8em3nrNSkqJySMqLrVoMNskyTXVg1caFvaYfdR34EvKSR6sd
            aZY6sJhxO2RhjZp12Vx0IaeIsfJgmzVdg30c63DUNDY9wOY7le8KB1pLqiKAbWps
            8EArb9sG4RdY742M/s9JPNWQza3IhZqGjluJf3WLyUN2bfbldBRW2cPC56Nf31zS
            XgEpqatodDPyzYfrxpIMZEDdbRqqJw90dpwRGMgpDbm8aXNX90CeuSfuGQq7+DJj
            kWRhcZwdndHMu0N7T1UqhwB6g9Hf/r3K7VFOZzXXLYB3s46h/4erTRWTX06jtME=
            =PW4/
            -----END PGP MESSAGE-----
          fp: F385A8645CA55C0AA5D1263D9B05BF264528D991
    version: 3.13.3
