apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gorilla-rfjh2-apps
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-rfjh2
  dependsOn:
    - name: gorilla-secrets
  interval: 1m
  path: "./management-clusters/gorilla/workload-clusters/rfjh2/apps"
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: workload-clusters-fleet
  timeout: 1m
