apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${workload_cluster_name}-hello-world
spec:
  userConfig:
    configMap:
      name: ${workload_cluster_name}-hello-world-user-values
