apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
configMapGenerator:
  - behavior: replace
    files:
      - values=override_config_hello_world.yaml
    name: ${cluster_name}-hello-world-values
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
resources:
  - ../../../../app_sets/hello-web-app/
