replicaCount: 3
ingress:
  className: nginx # has to be in sync with the ingress class served by the cluster's ingress controller
  hosts:
    - host: hello.cluster-template.example.com
      paths:
        - path: /
          pathType: Prefix
