apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-hello-world-standalone
  namespace: org-${organization}
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: false
  name: hello-world-app
  namespace: hello-world
  version: 0.2.0
