apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mc-name-gitops  # TODO: change "mc-name" to your Management Cluster name
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-master
  interval: 1m0s
  path: ./management-clusters/MC_NAME
  # Top level kustomizations may have prune set to `true`
  # only if they do not handle cluster creation.
  #
  # Where cluster creation is being handled, this should default to false
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: your-repo  # TODO: change "your-repo" to the name of GitRepository pointing to your GitOps repo
  timeout: 2m0s
