apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mc-name-gitops  # TODO: change "mc-name" to your Management Cluster name
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-master
  interval: 1m0s
  path: ./management-clusters/MC_NAME
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: your-repo  # TODO: change "your-repo" to the name of GitRepository pointing to your gitops repo
  timeout: 2m0s
