apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: MC_NAME-gitops # change mc-name
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-master
  interval: 1m0s
  path: ./management-clusters/MC_NAME
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: YOUR_REPO
  timeout: 2m0s
