apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mc-name-gitops
  namespace: default
spec:
  force: false
  interval: 1m0s
  path: ./management-clusters/MC_NAME
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: gitops-demo
  timeout: 2m0s
