apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-ingress-nginx
  namespace: org-${organization}
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: false
  name: ingress-nginx
  namespace: kube-system
  userConfig:
    configMap:
      name: ${cluster_name}-ingress-nginx-user-values
      namespace: org-multi-project
  version: 3.0.0
