apiVersion: v1
data:
  values: |-
    controller:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
    configmap:
      use-forwarded-headers: "false"
kind: ConfigMap
metadata:
  name: ${cluster_name}-ingress-nginx-user-values
  namespace: org-${organization}
