apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_id}-hello-world
spec:
  catalog: giantswarm
  config:
    configMap:
      name: ${cluster_id}-hello-world-values
      namespace: hello-world-app
  kubeConfig:
    inCluster: false
  name: hello-world-app
  namespace: hello-world-app
  version: 0.2.1
