apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-hello-world
  namespace: org-${organization}
spec:
  catalog: giantswarm
  config:
    configMap:
      name: ${cluster_name}-hello-world-values
      namespace: org-${organization}
  kubeConfig:
    inCluster: false
  name: hello-world-app
  namespace: org-${organization}
  version: 0.2.0
