apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  labels:
    giantswarm.io/cluster: ${cluster_name}
  name: ${cluster_name}-hello-world
  namespace: org-${organization}
spec:
  interval: 10m
  provider: generic
  ref:
    tag: 3.2.2
  url: oci://gsoci.azurecr.io/charts/giantswarm/hello-world
