apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: ${cluster_name}
  namespace: org-${organization}
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: true
  name: cluster-openstack
  namespace: org-${organization}
  version: ${cluster_release}
