apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}
  namespace: org-${organization}
spec:
  # See: https://docs.giantswarm.io/app-platform/app-configuration/#extra-configs
  extraConfigs:
    - name: ${cluster_name}-data-center-config
      namespace: org-${organization}
