replicaCount: 2
ingress:
  enabled: false
route:
  enabled: true
  kind: HTTPRoute
  parentRefs: # has to be in sync with the Gateway served by the cluster's Envoy Gateway
    - name: giantswarm-default
      namespace: envoy-gateway-system
  hostnames: # under the cluster's base domain and in the Gateway's `listeners.https.subdomains`
    - "hello.{{ .Values.baseDomain }}"
