replicaCount: 2
ingress:
  className: nginx # has to be in sync with the ingress class served by the cluster's ingress controller
  hosts:
    - host: hello.example.com
      paths:
        - path: /
          pathType: Prefix
