apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    giantswarm.io/managed-by: flux
  name: ignored
spec:
  config:
    configMap:
      name: rfjh2-cluster-values
      namespace: rfjh2
  kubeConfig:
    context:
      name: rfjh2
    inCluster: false
    secret:
      name: rfjh2-kubeconfig
      namespace: rfjh2
