global:
  nodePools:
    xxxxx:
      additionalSecurityGroups:
        - id: sg-0xxxxxxxxxxxxxx3f
      availabilityZones:
        - eu-west-1a
      instanceType: m6a.4xlarge
      minSize: 1
      maxSize: 10
