bastion:
  bootFromVolume: true
  diskSize: 10
  flavor: n1.tiny
  image: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
cloudConfig: cloud-config
cloudName: openstack
clusterName: ${cluster_name}
controlPlane:
  availabilityZones:
  - demo_az_1
  - demo_az_2
  - demo_az_3
  bootFromVolume: true
  diskSize: 50
  flavor: n1.small
  image: bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
  replicas: 3
externalNetworkID: cccccccc-cccc-cccc-cccc-cccccccccccc
kubernetesVersion: v1.20.9
nodeCIDR: 10.6.0.0/24
nodeClasses:
- bootFromVolume: true
  diskSize: 50
  flavor: n1.small
  image: dddddddd-dddd-dddd-dddd-dddddddddddd
  name: default
nodePools:
- class: default
  failureDomain: demo_az_1
  name: demo_az_1
  replicas: 1
- class: default
  failureDomain: demo_az_2
  name: demo_az_2
  replicas: 1
- class: default
  failureDomain: demo_az_3
  name: demo_az_3
  replicas: 1
organization: ${organization}
