apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}
  namespace: org-${organization}
spec:
  extraConfigs:
    - kind: configMap
      name: ${cluster_name}-config
      namespace: org-${organization}
      priority: 1
