apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: flux
  namespace: org-${organization}
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: false
  name: flux-app
  namespace: flux-app
  userConfig:
    configMap:
      name: ${cluster_id}-flux-app-user-values
      namespace: org-${organization}
  version: 0.11.0
