---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ${cluster_name}-hello-app
  namespace: org-${organization}
spec:
  filterTags:
    pattern: '.*-dev.*'
  imageRepositoryRef:
    name: ${cluster_name}-hello-app
  policy:
    semver:
      range: '>=0.1.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ${cluster_name}-simple-db-app
  namespace: org-${organization}
spec:
  imageRepositoryRef:
    name: ${cluster_name}-simple-db
  policy:
    semver:
      range: '>=0.1.0 <0.2.0'
