apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: clusters-capi-wc-name
  namespace: default
spec:
  interval: 1m
  path: "./management-clusters/MC_NAME/organizations/ORG_NAME/workload-clusters/CAPI_WC_NAME"
  postBuild:
    substitute:
      cluster_domain: "MY_DOMAIN"
      cluster_name: "CAPI_WC_NAME"
      cluster_release: "0.8.1"
      default_apps_release: "0.2.0"
      organization: "ORG_NAME"
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: REPO_NAME
  timeout: 2m
