apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ${workload_cluster_name}
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-FROM_TEMPLATE_WC_NAME
  interval: 1m
  path: "./management-clusters/MC_NAME/organizations/ORG_NAME/workload-clusters/FROM_TEMPLATE_WC_NAME"
  postBuild:
    substitute:
      cluster_id: "TMPL_WC_ID"
      control_plane_id: "TMPL_CP_ID"
      machine_deployment_id: "TMPL_MD_ID"
      organization: "ORG_NAME"
      release: "16.3.1"
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: ${gitops_repo}
  timeout: 2m
