apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: "hello-app-prod-eu-central"  # TODO: change 'hello-app-prod-eu-central' to your cluster name; must be a correct k8s resource name (DNS-like)
  namespace: default
spec:
  interval: 1m
  path: "./management-clusters/MC_NAME/organizations/ORG_NAME/workload-clusters/HELLO_APP_PROD_CLUSTER_EU_CENTRAL/mapi"
  postBuild:
    substitute:
      cluster_description: "description"
      cluster_domain: "env-prod-your-cluster-domain-name"  # TODO: change 'env-prod-your-cluster-domain-name' to real domain name
      cluster_name: "hello-app-prod-eu-central"  # TODO: change 'hello-app-prod-eu_central' to your cluster name; must be a correct k8s resource name (DNS-like)
      organization: "org-name"  # TODO: change 'org-name' to your organization name
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: your-repo  # TODO: change "your-repo" to the name of GitRepository pointing to your GitOps repo
  timeout: 2m
