apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: clusters-CAPI_WC_NAME
  namespace: default
spec:
  interval: 1m
  path: "./management-clusters/MC_NAME/organizations/ORG_NAME/workload-clusters/HELLO_APP_STAGING_CLUSTER_1"
  postBuild:
    substitute:
      cluster_domain: "MY_DOMAIN"
      cluster_id: "HELLO_APP_STAGING_1"
      cluster_name: "HELLO_APP_STAGING_1"
      cluster_release: "0.8.1"
      default_apps_release: "0.2.0"
      organization: "ORG_NAME"
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: REPO_NAME
  timeout: 2m
