apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
commonLabels:
  giantswarm.io/managed-by: flux
kind: Kustomization
resources:
- FROM_TEMPLATE_WC_NAME.yaml
- CAPI_WC_NAME.yaml
- WC_NAME.yaml
- HELLO_APP_PROD_CLUSTER_1.yaml
- HELLO_APP_STAGING_CLUSTER_1.yaml
- HELLO_APP_DEV_CLUSTER_1.yaml
- WC_NAME_NO_OUT_OF_BAND.yaml
- WC_NAME_OUT_OF_BAND_FLUX_APP.yaml
- WC_NAME_OUT_OF_BAND_NO_FLUX_APP.yaml
