apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
commonLabels:
  giantswarm.io/managed-by: flux
kind: Kustomization
resources:
  - CAPI_WC_NAME.yaml
  - HELLO_APP_DEV_CLUSTER_1.yaml
  - HELLO_APP_PROD_CLUSTER_1.yaml
  - HELLO_APP_STAGING_CLUSTER_1.yaml
  - CAPI_WC_NAME_OUT_OF_BAND_FLUX_APP.yaml
  - CAPI_WC_NAME_OUT_OF_BAND_NO_FLUX_APP.yaml
