apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: MC_NAME-clusters-WC_NAME-mapi
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-WC_NAME
  interval: 1m
  path: "./management-clusters/MC_NAME/organizations/ORG_NAME/workload-clusters/WC_NAME_OUT_OF_BAND_NO_FLUX_APP/mapi"
  postBuild:
    substitute:
      cluster_id: "WC_ID"
      control_plane_id: "CP_ID"
      machine_deployment_id: "MD_ID"
      organization: "ORG_NAME"
      release: "16.3.1"
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: REPO_NAME
  timeout: 2m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: MC_NAME-clusters-WC_NAME-direct
  namespace: default
spec:
  interval: 1m
  kubeConfig:
    secretRef:
      name: WC_NAME-kubeconfig
  path: "./management-clusters/MC_NAME/organizations/ORG_NAME/workload-clusters/WC_NAME_OUT_OF_BAND_NO_FLUX_APP/out-of-band"
  postBuild:
    substitute:
      cluster_id: "WC_ID"
      organization: "ORG_NAME"
  prune: true
  sourceRef:
    kind: GitRepository
    name: REPO_NAME
  timeout: 2m
