apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ${workload_cluster_name}
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-WC_NAME
  interval: 1m
  path: "./management-clusters/MC_NAME/organizations/ORG_NAME/workload-clusters/WC_NAME"
  postBuild:
    substitute:
      cluster_id: "WC_ID"
      control_plane_id: "CP_ID"
      machine_deployment_id: "MD_ID"
      organization: "ORG_NAME"
      release: "16.3.1"
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: ${gitops_repo}
  timeout: 2m
