apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusters-mapi-out-of-band-no-flux  # TODO: change to your cluster name; must be a correct k8s resource name (DNS-like)
  namespace: default
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg-wc-name
  interval: 1m
  path: "./management-clusters/MC_NAME/organizations/ORG_NAME/workload-clusters/WC_NAME_OUT_OF_BAND_NO_FLUX_APP/mapi"
  postBuild:
    substitute:
      cluster_description: "description"
      cluster_domain: "your-cluster-domain-name"  # TODO: change 'your-cluster-domain-name' to real domain name
      cluster_name: "mapi-out-of-band-no-flux"
      cluster_release: "0.8.1"
      default_apps_release: "0.2.0"
      organization: "org-name"  # TODO: change 'org-name' to your organization name
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: your-repo  # TODO: change "your-repo" to the name of GitRepository pointing to your GitOps repo
  timeout: 2m
