apiVersion: v1
data:
  values: |
    bastion:
      bootFromVolume: true
      diskSize: 50
      flavor: n1.tiny
      image: 8f0ccaf8-501e-4760-97cc-fbb8b812eb50
    cloudConfig: cloud-config-giantswarm-2
    cloudName: openstack
    clusterName: flux01
    controlPlane:
      bootFromVolume: true
      diskSize: 50
      flavor: n1.small
      image: 857c9ff3-ac41-4aa3-bfde-2bb0cc4600f1
      replicas: 1
    externalNetworkID: cdbcb519-1f91-43fb-b0a9-312f0abf8f12
    kubernetesVersion: v1.20.9
    nodeCIDR: 10.6.0.0/24
    nodeClasses:
    - bootFromVolume: true
      diskSize: 50
      flavor: n1.small
      image: 857c9ff3-ac41-4aa3-bfde-2bb0cc4600f1
      name: default
    nodePools:
    - class: default
      failureDomain: gb-lon-1
      name: default
      replicas: 3
    oidc:
      caFile: ""
      clientId: dex-k8s-authenticator
      groupsClaim: groups
      issuerUrl: https://dex.flux01.test.gigantic.io
      usernameClaim: email
    organization: multi-project
kind: ConfigMap
metadata:
  name: flux01-userconfig
  namespace: org-multi-project
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/managed-by: flux
  name: flux01
  namespace: org-multi-project
spec:
  catalog: giantswarm-test
  kubeConfig:
    inCluster: true
  name: cluster-openstack
  namespace: org-multi-project
  userConfig:
    configMap:
      name: flux01-userconfig
      namespace: org-multi-project
  version: 0.5.0-cbde804a0c497463cb0cc37262268667bb015b51
---
apiVersion: v1
data:
  values: |
    clusterName: flux01
    organization: multi-project
kind: ConfigMap
metadata:
  name: flux01-default-apps-userconfig
  namespace: org-multi-project
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    giantswarm.io/managed-by: flux
  name: flux01-default-apps
  namespace: org-multi-project
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: true
  name: default-apps-openstack
  namespace: org-multi-project
  userConfig:
    configMap:
      name: flux01-default-apps-userconfig
      namespace: org-multi-project
  version: 0.1.0
