apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-ingress-nginx
  namespace: kube-system
spec:
  userConfig:
    configMap:
      name: ${cluster_name}-tmpl-ingress-nginx-user-values
      namespace: kube-system
    secret:
      name: ${cluster_name}-tmpl-ingress-nginx-user-secret
      namespace: kube-system
