apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ${cluster_name}-hello-world
  namespace: org-${organization}
spec:
  imageRepositoryRef:
    name: ${cluster_name}-hello-world
    namespace: org-${organization}
  policy:
    semver:
      range: '>=0.0.0'
