apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
commonLabels:
  giantswarm.io/cluster: ${cluster_name}
  giantswarm.io/managed-by: flux
kind: Kustomization
resources:
  - hello-world/helmrelease.yaml
  - hello-world/ocirepository.yaml
  - hello-world-automatic-updates/helmrelease.yaml
  - hello-world-automatic-updates/ocirepository.yaml
  - hello-world-automatic-updates/imagepolicy.yaml
  - hello-world-automatic-updates/imagerepository.yaml
  - ingress-nginx-from-template/
  - ingress-nginx/configmap.yaml
  - ingress-nginx/helmrelease.yaml
  - ingress-nginx/ocirepository.yaml
