apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
commonLabels:
  giantswarm.io/managed-by: flux
configMapGenerator:
  - files:
      - values=nginx-from-template/override_config_nginx_ingress_controller.yaml
    name: ${cluster_id}-nginx-ingress-controller-user-values
kind: Kustomization
patchesStrategicMerge:
  - nginx-from-template/patch_nginx_ingress_config.yaml
resources:
  - hello-world/appcr.yaml
  - hello-world-automatic-updates/appcr.yaml
  - hello-world-automatic-updates/imagepolicy.yaml
  - hello-world-automatic-updates/imagerepository.yaml
  - nginx-from-template/override_secret_nginx_ingress_controller.enc.yaml
