apiVersion: kustomize.config.k8s.io/v1beta1
buildMetadata: [originAnnotations]
commonLabels:
  giantswarm.io/managed-by: flux
kind: Kustomization
resources:
  - hello-world/appcr.yaml
  - hello-world-automatic-updates/appcr.yaml
  - hello-world-automatic-updates/imagepolicy.yaml
  - hello-world-automatic-updates/imagerepository.yaml
  - ingress-nginx-from-template/
  - ingress-nginx/appcr.yaml
  - ingress-nginx/configmap.yaml
