#!/bin/bash

set -e
set -o pipefail

help() {
	echo -e "
Test syntax using fake-flux-build helper. Must be run from repo root dir (a dir that contains
'management-clusters' dir).

Usage: $0 [validate|template]

"
	exit 1
}

KUBERNETES_VERSION="master"

KUBERNETES_SCHEMA_REPOSITORY="https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/${KUBERNETES_VERSION}/"
GS_SCHEMA_REPOSITORY="https://raw.githubusercontent.com/giantswarm/json-schema/main/master"

GS_SCHEMA_REPOSITORY_CACHE="/tmp/gs-schema-repository-cache"
mkdir -p "${GS_SCHEMA_REPOSITORY_CACHE}"

test() {
	mode="$1"
	mc_dir="management-clusters"
	for mc in $(find ${mc_dir}/ -maxdepth 1 -type d ! -path ${mc_dir}/); do
		mc_name=${mc##*/}
		org_dir="${mc}/organizations"
		for org in $(find "${org_dir}"/ -maxdepth 1 -type d ! -path "${org_dir}"/); do
			org_name=${org##*/}
			wc_dir="${org}/workload-clusters"
			for wc in $(find "${wc_dir}"/ -maxdepth 1 -type d ! -path "${wc_dir}"/); do
				wc_name=${wc##*/}
				dir_list=""
				if [[ -f "$wc/kustomization.yaml" ]]; then
					dir_list="/"
				else
					dir_list=$(find "${wc}"/ -maxdepth 1 -type d ! -path "${wc}"/)
				fi
				for dir_name in $dir_list; do
					if [[ "$dir_name" != "/" ]]; then
						dir_name=${dir_name##*/}
					fi
					if [[ "$mode" == "validate" ]]; then
						has_validation_errors=0

						echo "Testing: $mc_name $org_name $wc_name $dir_name"

						echo -n "yamllint: "
						if ! ./tools/fake-flux-build build "$mc_name" "$org_name" "$wc_name" "$dir_name" | yamllint -; then has_validation_errors=1; else echo "OK"; fi

						echo -n "kubeconform: "
						if ! ./tools/fake-flux-build build "$mc_name" "$org_name" "$wc_name" "$dir_name" |
							kubeconform -ignore-missing-schemas -schema-location="${KUBERNETES_SCHEMA_REPOSITORY}/{{ .ResourceKind }}{{ .KindSuffix }}.json" -schema-location "${GS_SCHEMA_REPOSITORY}/{{ .ResourceKind }}{{ .KindSuffix }}.json" -cache "${GS_SCHEMA_REPOSITORY_CACHE}" -output text; then has_validation_errors=1; else echo "OK"; fi

						echo ""

						if [[ ${has_validation_errors} -ne 0 ]]; then
							exit 2
						fi
					else
						echo "---"
						./tools/fake-flux-build build "$mc_name" "$org_name" "$wc_name" "$dir_name"
					fi
				done
			done
		done
	done
}

if [[ $# -gt 1 ]]; then
	help
	exit 1
fi

case "$1" in
validate | template)
	test "$1"
	;;
*)
	help
	;;
esac
