#!/bin/bash

set -e

help() {
    echo -e "
Test syntax using fake-flux-build helper. Must be run from repo root dir (a dir that contains
'management-clusters' dir).

"
    exit 1
}

test() {

    mc_dir="management-clusters"
    for mc in $(find ${mc_dir}/ -maxdepth 1 -type d ! -path ${mc_dir}/); do
        mc_name=${mc##*/}
        org_dir="${mc}/organizations"
        for org in $(find ${org_dir}/ -maxdepth 1 -type d ! -path ${org_dir}/); do
            org_name=${org##*/}
            wc_dir="${org}/workload-clusters"
            for wc in $(find ${wc_dir}/ -maxdepth 1 -type d ! -path ${wc_dir}/); do
                wc_name=${wc##*/}
                for d in $(find ${wc}/ -maxdepth 1 -type d ! -path ${wc}/); do
                    dir_name=${d##*/}
                    echo "Testing: $mc_name $org_name $wc_name $dir_name"
                    echo -n "yamllint: "
                    ./tools/fake-flux-build build $mc_name $org_name $wc_name $dir_name | yamllint - && echo "OK"
                    echo "kubeval: "
                    ./tools/fake-flux-build build $mc_name $org_name $wc_name $dir_name | kubeval --ignore-missing-schemas
                    echo ""
                done
            done
        done
    done
}

if [[ $# -gt 0 ]]; then
    help
    exit 1
fi

test
