global:
  nodePools:
    xxxxx:
      additionalSecurityGroups:
        - id: sg-0xxxxxxxxxxxxxx3f
      availabilityZones:
        - eu-central-1a
      instanceType: m6a.2xlarge
      minSize: 1
      maxSize: 10
