apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_id}-hello-world
  namespace: demo0
spec:
  catalog: giantswarm
  name: hello-world-app
  namespace: hello-world
  version: 0.2.0
