---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: org-multi-project
patches:
  - path: cluster_config.yaml
    target:
      kind: App
resources:
  - nginx-ingress-controller/appcr.yaml
  - nginx-ingress-controller/configmap.yaml
  - dex/appcr.yaml
  - dex/configmap.yaml
