apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: ${cluster_name}-ingress-nginx
  namespace: kube-system
spec:
  catalog: giantswarm
  extraConfigs:
    - kind: configMap
      name: ${cluster_name}-ingress-nginx-values
      namespace: kube-system
      priority: 1
  kubeConfig:
    inCluster: false
  name: ingress-nginx
  namespace: kube-system
  version: 3.0.0
