apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  annotations:
    giantswarm.io/docs: https://docs.giantswarm.io/ui-api/management-api/crd/clusters.cluster.x-k8s.io/
  labels:
    cluster.x-k8s.io/cluster-name: ${cluster_id}
    giantswarm.io/cluster: ${cluster_id}
    giantswarm.io/organization: ${organization}
    release.giantswarm.io/version: ${release}
  name: ${cluster_id}
  namespace: org-${organization}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  infrastructureRef:
    apiVersion: infrastructure.giantswarm.io/v1alpha3
    kind: AWSCluster
    name: ${cluster_id}
    namespace: org-${organization}
