name: diff preview

on:
  pull_request:
  push:
    branches: [HEAD_BRANCH, main]

jobs:
  get-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-ffb-deps.yaml
      - uses: actions/checkout@v3
        #      - name: yq - portable yaml processor
        #uses: mikefarah/yq@v4.25.2
      - name: template all for the new branch
        run: ./tools/test-all-ffb template
