name: diff preview

on:
  pull_request:
  push:
    branches: [HEAD_BRANCH, main]

jobs:
  get-diff:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y yamllint
      - uses: giantswarm/install-binary-action@v1
        with:
          binary: kubeval
          download_url: "https://github.com/instrumenta/kubeval/releases/${version}/download/kubeval-linux-amd64.tar.gz"
          smoke_test: "${binary} --version"
          tarball_binary_path: "${binary}"
          version: "latest"
      - uses: actions/checkout@v3
      - name: template all for the new branch
        run: ./tools/test-all-ffb template > /tmp/new.yaml
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          path: 'old'
      - name: template all for the old branch
        run: cd old/ && ../tools/test-all-ffb template > /tmp/old.yaml && cd ..
      - name: save the diff
        run: diff /tmp/old.yaml /tmp/new.yaml
