name: diff preview

on:
  pull_request:
  push:
    branches: [HEAD_BRANCH]

jobs:
  get-diff:
    runs-on: ubuntu-latest
    env:
      dyff_ver: 1.5.4
      kubeconform_ver: 0.4.13
    steps:
      - run: sudo apt-get install -y yamllint
      - name: install dyff
        uses: giantswarm/install-binary-action@v1
        with:
          binary: dyff
          download_url: "https://github.com/homeport/dyff/releases/download/v${version}/dyff_${version}_linux_amd64.tar.gz"
          smoke_test: "${binary} version"
          tarball_binary_path: "${binary}"
          version: ${{ env.dyff_ver }}
      - run: which dyff
      - uses: giantswarm/install-binary-action@v1
        with:
          binary: kubeconform
          download_url: "https://github.com/yannh/kubeconform/releases/download/v${version}/kubeconform-linux-amd64.tar.gz"
          smoke_test: "${binary} -v"
          tarball_binary_path: "${binary}"
          version: ${{ env.kubeconform_ver }}
      - run: which kubeconform
      - run: ls -la /opt/hostedtoolcache
      - uses: actions/checkout@v3
      - name: template all for the new branch
        run: ./tools/test-all-ffb template > /tmp/new.yaml
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          path: 'old'
      - name: template all for the old branch
        run: cd old/ && ../tools/test-all-ffb template > /tmp/old.yaml && cd ..
      - name: save the diff
        uses: mathiasvr/command-output@v1
        id: diff
        with:
          run: 'dyff between -s -i -b -g /tmp/old.yaml /tmp/new.yaml && echo "No diff detected" || if [[ $? -eq 255 ]]; then echo "Diff error"; fi;'
      - name: Find diff comment
        uses: peter-evans/find-comment@v2
        continue-on-error: true
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Rendered manifest diff output log
      - name: Delete old comment
        uses: jungwinter/comment@v1
        continue-on-error: true
        with:
          type: delete
          comment_id: ${{ steps.fc.outputs.comment-id }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create or update validation comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <details>
            <summary> Rendered manifest diff output log </summary>
            <!-- mandatory empty line -->
            ${{ steps.diff.outputs.stdout }}
            </details>
            <!-- mandatory empty line -->
