name: diff preview

on:
  pull_request:
  push:
    branches: [HEAD_BRANCH, main]

jobs:
  get-diff:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y yamllint
      - uses: giantswarm/install-binary-action@v1
        with:
          binary: kubeval
          download_url: "https://github.com/instrumenta/kubeval/releases/${version}/download/kubeval-linux-amd64.tar.gz"
          smoke_test: "${binary} --version"
          tarball_binary_path: "${binary}"
          version: "latest"
      - uses: actions/checkout@v3
        #      - name: yq - portable yaml processor
        #uses: mikefarah/yq@v4.25.2
      - name: template all for the new branch
        run: ./tools/test-all-ffb template
