name: setup fake-flux-build dependencies

on:
  workflow_call:

jobs:
  setup_ffb:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y yamllint
      - uses: giantswarm/install-binary-action@v1
        with:
          binary: kubeval
          download_url: "https://github.com/instrumenta/kubeval/releases/${version}/download/kubeval-linux-amd64.tar.gz"
          smoke_test: "${binary} --version"
          tarball_binary_path: "${binary}"
          version: "latest"
