name: run tests on kind

on:
  pull_request:
  push:
    branches: [HEAD_BRANCH]

jobs:
  test_on_kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
      - name: extract kind kube.config
        run: kind get kubeconfig > /tmp/kube.config
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv
      - name: install pipenv environment
        run: cd tests/ats && pipenv install --deploy
      # TODO: setup env vars
      - name: run tests
        run: cd tests/ats && pipenv run pytest .
