name: run tests on kind

on:
  pull_request:
  push:
    branches: [HEAD_BRANCH]

jobs:
  test_on_kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
      - name: extract kind kube.config
        run: kind get kubeconfig --name 'chart-testing' > /tmp/kube.config
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv
      - name: install pipenv environment
        run: cd tests/ats && pipenv install --deploy
      - name: run tests
        run: cd tests/ats && pipenv run pytest .
        env:
          KUBECONFIG: /tmp/kube.config
          GITOPS_FLUX_APP_VERSION: "0.13.0"
          GITOPS_INIT_NAMESPACES: "default,org-org-name"
          GITOPS_REPO_BRANCH: "${{ github.head_ref }}"
          GITOPS_REPO_URL: "https://github.com/giantswarm/gitops-template"
