apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gamma-flux01
  namespace: flux-system
spec:
  interval: 1m
  path: "./management-clusters/gamma/workload-clusters/flux01"
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: workload-clusters-fleet
  timeout: 1m
