apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: ${cluster_name}-hello-world
spec:
  imageRepositoryRef:
    name: ${cluster_name}-hello-world
  policy:
    semver:
      range: '>=0.0.0'
